### ISSUE TITLE
rostest tag is not parsed properly

### ISSUE THREAD

**Issue by tigelbri** [bponsler/roslaunch_to_dot#12]
When using the tool with a launch file including a rostest tag the following error occurs:

Traceback (most recent call last):
  File "./roslaunch-to-dot.py", line 763, in __parseLaunchElements
    testNode = self.__parseTestNodeTag(child)
  File "./roslaunch-to-dot.py", line 1007, in __parseTestNodeTag
    ifArg = self.__getArgumentForConditional(node, self.IfAttribute)
NameError: global name 'node' is not defined

But definitely a cool tool :)

Cheers 
Tristan

**Comment by bponsler** [comment]
Nice find, and thanks for reporting this. I'll take a look at it.

**Comment by bponsler** [comment]
I fixed this issue (typos). See commit d44d36d308cf87fc67a081bd6d5494b1634740ba

Thanks for reporting this. Can you test this to see if it works for you?
